### ISSUE TITLE
Microsoft.OData.Client <7.6.3 support

### ISSUE THREAD

**Issue by joostmeijles** [OData/ODataConnectedService#85] opened 2020-04-01 12:47 UTC
### Describe the bug
I cannot generate OData services because my service is not compatible with Microsoft.OData.Client 7.6.3. 

#### Version of the Project affected
ODataConnectedService > v0.5.x

#### Expected behavior
A way to download an older version, ie. v0.4.

#### Actual behavior
No downloads for < v0.5 available.

**Comment by joostmeijles** [comment] 2020-04-02 08:44
As workaround I built a v0.4.0 from commit 837694203af274c760a5c46c8305ccf982101501 and performed: `sn.exe -Vr ODataConnectedService\src\bin\Debug\Microsoft.OData.ConnectedService.dll` to run it locally, but that's clearly not ideal.

**Comment by habbes** [comment] 2020-04-02 14:47
@joostmeijles let me know if that version works for you. We could add v0.4.0 to our GitHub releases: https://github.com/OData/ODataConnectedService/releases

**Comment by joostmeijles** [comment] 2020-04-02 14:56
@habbes would prefer an older release that does not use the `CdslReader`. Would that be v0.3?

**Comment by habbes** [comment] 2020-04-02 16:26
@joostmeijles v0.3 did not use CsdlReader.

**Comment by joostmeijles** [comment] 2020-04-02 17:36
> @joostmeijles v0.3 did not use CsdlReader.

That’s what I need. Please add release v0.3 (including vsix). 

Thanks a lot!

**Comment by joostmeijles** [comment] 2020-04-21 14:16
@habbes any update?

**Comment by gralov** [comment] 2020-05-12 07:49
Hi, I'm in the same position. Not being able to upgrade the Microsoft.OData.Client library. I would very much appreciate being able to get the get older versions of the extension. Would that be possible?

**Comment by caroen** [comment] 2020-06-02 07:24
Here a shameless bump! (I am also in need of the 0.4.0 client which supports the 6.x version of OData)

**Comment by habbes** [comment] 2020-06-10 08:01
Hey @joostmeijles  @gralov  @caroen  working on getting a release compatible with 6.x and that's also compatible with VS 2019. ETA sometime this week.

**Comment by habbes** [comment] 2020-07-07 14:35
Hi @joostmeijles @gralov  @caroen, apologies for the delay. Could you check whether this release works for you: https://github.com/OData/ODataConnectedService/releases/tag/v0.3.1

**Comment by caroen** [comment] 2020-07-09 06:50
hi @habbes thanks for getting it up, however i've now installed in VS2019 and i am not seeing the "Update OData Connected Services" option in the right click menu:

![image](https://user-images.githubusercontent.com/1478224/87006625-480ecd80-c1c1-11ea-9800-617f16f180bd.png)
![image](https://user-images.githubusercontent.com/1478224/87006630-4c3aeb00-c1c1-11ea-897e-90a2a1cb8db0.png)

**Comment by habbes** [comment] 2020-07-09 07:38
Hi @caroen glad to see you were able to set it up. I think if you want to install a newer version you can uninstall the 0.3.1 and install the latest version directly from the VS Studio extensions manager.

May ask why you want the update button enabled if you preferred to install that specific version? New versions of the extension don't support older version of the OData client, and that was the whole point of providing this version.

**Comment by caroen** [comment] 2020-07-09 08:07
Hi @habbes sry for the confusion, the 2nd image was just to verify that i had version 0.3.1 installed, its the first screenshot where i would the expect the "Update OData Connected Service..." option to appear when right clicking :)

**Comment by habbes** [comment] 2020-07-09 13:14
@caroen  thanks for the clarification. I will investigate the issue and get back.

**Comment by habbes** [comment] 2020-07-14 07:58
@caroen I was not able to reproduce the issue, I can see the "Update OData Connected Service"
![image](https://user-images.githubusercontent.com/8460169/87399870-b4723e00-c5c0-11ea-9f2c-08e6b733ccb1.png)

Was that a connected service that already existed in your project prior to the upgrade, or was it a new one you created to test out the version? If it was a pre-existing one, could you try creating a new one with similar settings and checking whether that's updatable?

**Comment by habbes** [comment] 2020-07-22 07:02
@caroen I have a hunch the issue could also be related to you upgrading from VS 2017 to 2019. Maybe VS 2019 didn't recognize the folder as a connected service. In that case, maybe re-creating the connected service in VS 2019 with the same settings would help. I'm going to go ahead and close this issue. Feel free to open an issue if you still face problems.

**Closed by habbes** 2020-07-22 07:02 UTC
Labels: question

**Comment by chenowen** [comment] 2020-07-29 07:29
I have exactly same issue as @caroen

**Comment by Benjamin-S-Olsen** [comment] 2020-07-31 11:52
I have the same problem as @caroen and @chenowen. I uninstalled the service as 0.10.0 and reinstalled 0.3.1 on vs 2017, and can no longer update odata on the existing connections from before the downgrade and I'm also not able to create a new odata connection. Updating it back to 0.10.0 makes the odata update functionality reapear, but downgrading it to at least under 0.5.0 makes it disappear.
![image](https://user-images.githubusercontent.com/69040732/89032276-9d5b7c00-d334-11ea-818a-277f6ac8b0f1.png)

**Comment by MP753** [comment] 2020-08-05 14:19
Had the same problem, this helped me https://kb.sitecore.net/articles/534956.
