### ISSUE TITLE
Any plans to make it work in VS 2022?

### ISSUE THREAD

**Issue by fscopel** [OData/ODataConnectedService#231] opened 2021-11-10 02:05 UTC
Just wondering if there are plans to make it work with VS 2022?

**Comment by ImGonaRot** [comment] 2021-11-19 14:04
This is a duplicate of #225

**Comment by habbes** [comment] 2022-01-25 13:26
Hi @fscopel  @ImGonaRot we do plan to add support for VS2022, we'll update this thread when we have an ETA.

**Comment by julealgon** [comment] 2022-06-09 13:24
@habbes do you have any updates to share here?

**Comment by ElizabethOkerio** [comment] 2022-08-12 05:19
Check out the latest release https://marketplace.visualstudio.com/items?itemName=marketplace.ODataConnectedService2022

**Closed by ElizabethOkerio** 2022-08-12 05:19 UTC
Labels: Feature
