### ISSUE TITLE
Adding OData Connected Service to the project failed: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by fxvits** [OData/ODataConnectedService#137] opened 2020-06-04 07:40 UTC
### Describe the bug
Each time I try to add/update an Odata Connected Service (Even with the Tripin Api provided on the Odata website (https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin)) , I get the following error :
Adding Nuget Packages...
Nuget Package "Microsoft.OData.Client" for OData client already installed.
Nuget Package "Microsoft.OData.Core" for OData client already installed.
Nuget Package "Microsoft.OData.Edm" for OData client already installed.
Nuget Package "Microsoft.Spatial" for OData client already installed.
Nuget Packages were installed.
Generating Client Proxy for OData V4...
Error:Adding OData Connected Service to the project failed: Value does not fall within the expected range.

#### Version of the Project affected
ODataConnectedService v0.10.0
Microsoft Visual Studio Professional 2019 Version 16.5.2
Microsoft.Odata.Client v7.6.4

#### To Reproduce
1. Download the trip in API from https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin
2. Create an empty client windows project 
3. Right click on service Reference and select connected service => Odata connected service
4. In the wizard, I leave everything by default I just set the address to the local running tripin api (http://localhost:xxxx/$metadata)

#### Expected behavior
I expect to get the generated client Csdl

#### Actual behavior
Failing

#### Screenshots
![image](https://user-images.githubusercontent.com/4292179/83728966-493f5e80-a647-11ea-9eab-1bb523738b0d.png)

**Comment by mukeshrebari** [comment] 2020-06-12 10:16
![image](https://user-images.githubusercontent.com/30521476/84492387-bc8a4580-acc3-11ea-8a88-8818abd66fa5.png)
Even I am getting this error. I have recently update *OData Connected Service* Plugin. Since then it started giving me error.

**Comment by mukeshrebari** [comment] 2020-06-12 11:00
> ![image](https://user-images.githubusercontent.com/30521476/84492387-bc8a4580-acc3-11ea-8a88-8818abd66fa5.png)
> Even I am getting this error. I have recently update _OData Connected Service_ Plugin. Since then it started giving me error.

I have downgraded Plugin to Version 0.9.0 but still it is giving same error.

**Comment by SuperJMN** [comment] 2020-09-16 20:28
Same to me

**Comment by unchase** [comment] 2020-11-20 20:03
I can't reproduce the issue with ODataConnectedService v0.11.1.

**Comment by dvoelkel** [comment] 2021-03-16 05:37
I have the same problem with VS2019, while generating a d365-client.
The error occurs only in a webservice-project. 
New project can read the metadata and generate the proxy.
So I think it's a problem within the underlying project.

**Comment by habbes** [comment] 2022-02-25 08:38
Closing issue because we have not been able to reproduce it. If there's additional information that may help us reproduce the issue, kindly share it and re-open the issue.

**Closed by habbes** 2022-02-25 08:38 UTC

**Comment by kapsiR** [comment] 2023-02-15 12:47
@habbes We are experiencing the same problem as described here. Can you provide additional details how we can gain more error details than just this error message? 

> Error:Adding OData Connected Service to the project failed: Value does not fall within the expected range.

Thanks
